name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Sidebar Navigation
        - Nav Customizer
        - Drag & Drop
        - Icons
        - API Endpoints
        - Preferences Storage
        - Other
    validations:
      required: true
